name: Feature Request
description: 추가할 기능이 있을 때 작성해주세요.
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        양식에 맞춰 추가해야 할 기능을 적어주세요.
  - type: textarea
    attributes:
      label: 기능 설명
      description: 어떤 기능인지 설명해주세요.
      placeholder: 어떤 기능인지 설명해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 요구사항
      description: 기능이 구현됐을 때 어떻게 동작해야 하는지 적어주세요.
      placeholder: 기능이 구현됐을 때 어떻게 동작해야 하는지 적어주세요.
    validations:
      required: true

